### ISSUE TITLE
base aggregate view should trap focus while doing a transition

### ISSUE THREAD

**Issue by georgejecook** [georgejecook/maestro-roku#265]

**Comment by MannyNBA** [comment]
The bug is that the focus remains on the list while the transition is occurring, which enables additional key presses to be handled. The correct implementation should be that before the transition occurs, the focus must be moved from the list to a non-responsive component, so that subsequent key presses are not registered during transitions.

The workaround we're going with for now is to set focus to our loading indicator when `onItemSelected` is triggered.
